### ISSUE TITLE
Inclusion of MakeMakefile clobbers Object namespace

### ISSUE THREAD

**Issue by skahlert** [dignoe/graphicsmagick#6]
I had the problem that weird references to `#<UNIXSocket:<STDOUT>>` were popping up left right and center in my project.
After some investigation they all seemed to have a call to a method called "message" in common.
Some digging revealed, that MakeMakefile was included into Object and that module has a method called message.

Cause seems to be this line `require 'mkmf'` here:
https://github.com/dignoe/graphicsmagick/blob/master/lib/graphicsmagick.rb#L1

**Comment by dignoe** [comment]
Please patch this and create a pull request.
