### ISSUE TITLE
Getting the width using the identify.width doesn't work

### ISSUE THREAD

**Issue by suthanbala** [dignoe/graphicsmagick#7]
My Code is as follows:
```
img = GraphicsMagick::Image.new("public/media/#{filename}")
return img.identify.width
```

It returns `0`, however if I try `return img.identify.height` it returns the correct height. Any way to fix it?

**Comment by dignoe** [comment]
The width function works for me. If you find a bug, please either send in a full bug report or fork the repo and submit a pull request.
