### ISSUE TITLE
Ruby adding the backslash when inserting a symbol in the command

### ISSUE THREAD

**Issue by suthanbala** [dignoe/graphicsmagick#8]
**Code:**

    img.convert.size("300x300").thumbnail('300x250^').
    gravity("center").extent('300x250').write("public/#{path}/xs-" + filename)

**Produced Error Message:**

`GraphicsMagick::UnknownOptionError (gm convert  public/media/bbbb.JPG -size 300x300 -thumbnail 300x250\^ -gravity center -extent 300x250 public//media/xs-bbbb.JPG failed: gm convert: Option '-thumbnail' requires an argument or argument is malformed.
):`

**Environment**
Windows 10

**Comment by dignoe** [comment]
Please fork the repo, make the required changes, and submit a pull request.
